apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  selector:
    matchLabels:
      app: ${project.artifactId}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      strategy:
        type: Recreate
      containers:
      - name: default
        image: ${docker.image.name}:${docker.image.tag}
        imagePullPolicy: ${image.pull.policy}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
spec:
  selector:
    app: ${project.artifactId}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microstarter
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    # Unless quoted as string, controller doesn't honor this label
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /${project.artifactId}/*
        backend:
          serviceName: ${project.artifactId}
          servicePort: 80
